/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActualizarClaveRouteImport } from './routes/actualizar-clave'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as ImpuestosRouteImport } from './routes/impuestos'
import { Route as InvitacionRouteImport } from './routes/invitacion'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as RecuperarClaveRouteImport } from './routes/recuperar-clave'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as SoporteRouteImport } from './routes/soporte'
import { Route as VentasRouteImport } from './routes/ventas'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLandingRouteImport } from './routes/admin_.landing'
import { Route as AdminClientesIndexRouteImport } from './routes/admin/clientes/index'
import { Route as AdminClientesCompanyIdRouteImport } from './routes/admin/clientes/$companyId'
import { Route as AdminIaCreditosIndexRouteImport } from './routes/admin/ia-creditos/index'
import { Route as AdminIaCreditosConfiguracionRouteImport } from './routes/admin/ia-creditos/configuracion'
import { Route as AdminIaCreditosHistorialRouteImport } from './routes/admin/ia-creditos/historial'
import { Route as AdminMetricasIndexRouteImport } from './routes/admin/metricas/index'
import { Route as AdminMotorTributarioParidadRouteImport } from './routes/admin/motor-tributario/paridad'
import { Route as AdminMotorTributarioVersionesRouteImport } from './routes/admin/motor-tributario/versiones'
import { Route as AdminPlanesIndexRouteImport } from './routes/admin/planes/index'
import { Route as AdminPlanesPlanIdRouteImport } from './routes/admin/planes/$planId'
import { Route as AdminPlanesNuevoRouteImport } from './routes/admin/planes/nuevo'
import { Route as AdminTelemetriaIndexRouteImport } from './routes/admin/telemetria/index'
import { Route as AdminTelemetriaApiRouteImport } from './routes/admin/telemetria/api'
import { Route as AdminTelemetriaSiiRouteImport } from './routes/admin/telemetria/sii'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualizarClaveRoute = ActualizarClaveRouteImport.update({
  id: '/actualizar-clave',
  path: '/actualizar-clave',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpuestosRoute = ImpuestosRouteImport.update({
  id: '/impuestos',
  path: '/impuestos',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitacionRoute = InvitacionRouteImport.update({
  id: '/invitacion',
  path: '/invitacion',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarClaveRoute = RecuperarClaveRouteImport.update({
  id: '/recuperar-clave',
  path: '/recuperar-clave',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const SoporteRoute = SoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => rootRouteImport,
} as any)
const VentasRoute = VentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLandingRoute = AdminLandingRouteImport.update({
  id: '/admin_/landing',
  path: '/admin/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientesIndexRoute = AdminClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesCompanyIdRoute = AdminClientesCompanyIdRouteImport.update({
  id: '/clientes/$companyId',
  path: '/clientes/$companyId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIaCreditosIndexRoute = AdminIaCreditosIndexRouteImport.update({
  id: '/ia-creditos/',
  path: '/ia-creditos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIaCreditosConfiguracionRoute =
  AdminIaCreditosConfiguracionRouteImport.update({
    id: '/ia-creditos/configuracion',
    path: '/ia-creditos/configuracion',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminIaCreditosHistorialRoute =
  AdminIaCreditosHistorialRouteImport.update({
    id: '/ia-creditos/historial',
    path: '/ia-creditos/historial',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMetricasIndexRoute = AdminMetricasIndexRouteImport.update({
  id: '/metricas/',
  path: '/metricas/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMotorTributarioParidadRoute =
  AdminMotorTributarioParidadRouteImport.update({
    id: '/motor-tributario/paridad',
    path: '/motor-tributario/paridad',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMotorTributarioVersionesRoute =
  AdminMotorTributarioVersionesRouteImport.update({
    id: '/motor-tributario/versiones',
    path: '/motor-tributario/versiones',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPlanesIndexRoute = AdminPlanesIndexRouteImport.update({
  id: '/planes/',
  path: '/planes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanesPlanIdRoute = AdminPlanesPlanIdRouteImport.update({
  id: '/planes/$planId',
  path: '/planes/$planId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanesNuevoRoute = AdminPlanesNuevoRouteImport.update({
  id: '/planes/nuevo',
  path: '/planes/nuevo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTelemetriaIndexRoute = AdminTelemetriaIndexRouteImport.update({
  id: '/telemetria/',
  path: '/telemetria/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTelemetriaApiRoute = AdminTelemetriaApiRouteImport.update({
  id: '/telemetria/api',
  path: '/telemetria/api',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTelemetriaSiiRoute = AdminTelemetriaSiiRouteImport.update({
  id: '/telemetria/sii',
  path: '/telemetria/sii',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualizar-clave': typeof ActualizarClaveRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/compras': typeof ComprasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cuenta': typeof CuentaRoute
  '/demo': typeof DemoRoute
  '/documentos': typeof DocumentosRoute
  '/impuestos': typeof ImpuestosRoute
  '/invitacion': typeof InvitacionRoute
  '/metas': typeof MetasRoute
  '/onboarding': typeof OnboardingRoute
  '/planes': typeof PlanesRoute
  '/recuperar-clave': typeof RecuperarClaveRoute
  '/registro': typeof RegistroRoute
  '/soporte': typeof SoporteRoute
  '/ventas': typeof VentasRoute
  '/admin/landing': typeof AdminLandingRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clientes/$companyId': typeof AdminClientesCompanyIdRoute
  '/admin/ia-creditos/configuracion': typeof AdminIaCreditosConfiguracionRoute
  '/admin/ia-creditos/historial': typeof AdminIaCreditosHistorialRoute
  '/admin/motor-tributario/paridad': typeof AdminMotorTributarioParidadRoute
  '/admin/motor-tributario/versiones': typeof AdminMotorTributarioVersionesRoute
  '/admin/planes/$planId': typeof AdminPlanesPlanIdRoute
  '/admin/planes/nuevo': typeof AdminPlanesNuevoRoute
  '/admin/telemetria/api': typeof AdminTelemetriaApiRoute
  '/admin/telemetria/sii': typeof AdminTelemetriaSiiRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
  '/admin/ia-creditos/': typeof AdminIaCreditosIndexRoute
  '/admin/metricas/': typeof AdminMetricasIndexRoute
  '/admin/planes/': typeof AdminPlanesIndexRoute
  '/admin/telemetria/': typeof AdminTelemetriaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualizar-clave': typeof ActualizarClaveRoute
  '/auth': typeof AuthRoute
  '/compras': typeof ComprasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cuenta': typeof CuentaRoute
  '/demo': typeof DemoRoute
  '/documentos': typeof DocumentosRoute
  '/impuestos': typeof ImpuestosRoute
  '/invitacion': typeof InvitacionRoute
  '/metas': typeof MetasRoute
  '/onboarding': typeof OnboardingRoute
  '/planes': typeof PlanesRoute
  '/recuperar-clave': typeof RecuperarClaveRoute
  '/registro': typeof RegistroRoute
  '/soporte': typeof SoporteRoute
  '/ventas': typeof VentasRoute
  '/admin/landing': typeof AdminLandingRoute
  '/admin': typeof AdminIndexRoute
  '/admin/clientes/$companyId': typeof AdminClientesCompanyIdRoute
  '/admin/ia-creditos/configuracion': typeof AdminIaCreditosConfiguracionRoute
  '/admin/ia-creditos/historial': typeof AdminIaCreditosHistorialRoute
  '/admin/motor-tributario/paridad': typeof AdminMotorTributarioParidadRoute
  '/admin/motor-tributario/versiones': typeof AdminMotorTributarioVersionesRoute
  '/admin/planes/$planId': typeof AdminPlanesPlanIdRoute
  '/admin/planes/nuevo': typeof AdminPlanesNuevoRoute
  '/admin/telemetria/api': typeof AdminTelemetriaApiRoute
  '/admin/telemetria/sii': typeof AdminTelemetriaSiiRoute
  '/admin/clientes': typeof AdminClientesIndexRoute
  '/admin/ia-creditos': typeof AdminIaCreditosIndexRoute
  '/admin/metricas': typeof AdminMetricasIndexRoute
  '/admin/planes': typeof AdminPlanesIndexRoute
  '/admin/telemetria': typeof AdminTelemetriaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualizar-clave': typeof ActualizarClaveRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/compras': typeof ComprasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cuenta': typeof CuentaRoute
  '/demo': typeof DemoRoute
  '/documentos': typeof DocumentosRoute
  '/impuestos': typeof ImpuestosRoute
  '/invitacion': typeof InvitacionRoute
  '/metas': typeof MetasRoute
  '/onboarding': typeof OnboardingRoute
  '/planes': typeof PlanesRoute
  '/recuperar-clave': typeof RecuperarClaveRoute
  '/registro': typeof RegistroRoute
  '/soporte': typeof SoporteRoute
  '/ventas': typeof VentasRoute
  '/admin_/landing': typeof AdminLandingRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clientes/$companyId': typeof AdminClientesCompanyIdRoute
  '/admin/ia-creditos/configuracion': typeof AdminIaCreditosConfiguracionRoute
  '/admin/ia-creditos/historial': typeof AdminIaCreditosHistorialRoute
  '/admin/motor-tributario/paridad': typeof AdminMotorTributarioParidadRoute
  '/admin/motor-tributario/versiones': typeof AdminMotorTributarioVersionesRoute
  '/admin/planes/$planId': typeof AdminPlanesPlanIdRoute
  '/admin/planes/nuevo': typeof AdminPlanesNuevoRoute
  '/admin/telemetria/api': typeof AdminTelemetriaApiRoute
  '/admin/telemetria/sii': typeof AdminTelemetriaSiiRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
  '/admin/ia-creditos/': typeof AdminIaCreditosIndexRoute
  '/admin/metricas/': typeof AdminMetricasIndexRoute
  '/admin/planes/': typeof AdminPlanesIndexRoute
  '/admin/telemetria/': typeof AdminTelemetriaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualizar-clave'
    | '/admin'
    | '/auth'
    | '/compras'
    | '/configuracion'
    | '/cuenta'
    | '/demo'
    | '/documentos'
    | '/impuestos'
    | '/invitacion'
    | '/metas'
    | '/onboarding'
    | '/planes'
    | '/recuperar-clave'
    | '/registro'
    | '/soporte'
    | '/ventas'
    | '/admin/landing'
    | '/admin/'
    | '/admin/clientes/$companyId'
    | '/admin/ia-creditos/configuracion'
    | '/admin/ia-creditos/historial'
    | '/admin/motor-tributario/paridad'
    | '/admin/motor-tributario/versiones'
    | '/admin/planes/$planId'
    | '/admin/planes/nuevo'
    | '/admin/telemetria/api'
    | '/admin/telemetria/sii'
    | '/admin/clientes/'
    | '/admin/ia-creditos/'
    | '/admin/metricas/'
    | '/admin/planes/'
    | '/admin/telemetria/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualizar-clave'
    | '/auth'
    | '/compras'
    | '/configuracion'
    | '/cuenta'
    | '/demo'
    | '/documentos'
    | '/impuestos'
    | '/invitacion'
    | '/metas'
    | '/onboarding'
    | '/planes'
    | '/recuperar-clave'
    | '/registro'
    | '/soporte'
    | '/ventas'
    | '/admin/landing'
    | '/admin'
    | '/admin/clientes/$companyId'
    | '/admin/ia-creditos/configuracion'
    | '/admin/ia-creditos/historial'
    | '/admin/motor-tributario/paridad'
    | '/admin/motor-tributario/versiones'
    | '/admin/planes/$planId'
    | '/admin/planes/nuevo'
    | '/admin/telemetria/api'
    | '/admin/telemetria/sii'
    | '/admin/clientes'
    | '/admin/ia-creditos'
    | '/admin/metricas'
    | '/admin/planes'
    | '/admin/telemetria'
  id:
    | '__root__'
    | '/'
    | '/actualizar-clave'
    | '/admin'
    | '/auth'
    | '/compras'
    | '/configuracion'
    | '/cuenta'
    | '/demo'
    | '/documentos'
    | '/impuestos'
    | '/invitacion'
    | '/metas'
    | '/onboarding'
    | '/planes'
    | '/recuperar-clave'
    | '/registro'
    | '/soporte'
    | '/ventas'
    | '/admin_/landing'
    | '/admin/'
    | '/admin/clientes/$companyId'
    | '/admin/ia-creditos/configuracion'
    | '/admin/ia-creditos/historial'
    | '/admin/motor-tributario/paridad'
    | '/admin/motor-tributario/versiones'
    | '/admin/planes/$planId'
    | '/admin/planes/nuevo'
    | '/admin/telemetria/api'
    | '/admin/telemetria/sii'
    | '/admin/clientes/'
    | '/admin/ia-creditos/'
    | '/admin/metricas/'
    | '/admin/planes/'
    | '/admin/telemetria/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualizarClaveRoute: typeof ActualizarClaveRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComprasRoute: typeof ComprasRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  CuentaRoute: typeof CuentaRoute
  DemoRoute: typeof DemoRoute
  DocumentosRoute: typeof DocumentosRoute
  ImpuestosRoute: typeof ImpuestosRoute
  InvitacionRoute: typeof InvitacionRoute
  MetasRoute: typeof MetasRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanesRoute: typeof PlanesRoute
  RecuperarClaveRoute: typeof RecuperarClaveRoute
  RegistroRoute: typeof RegistroRoute
  SoporteRoute: typeof SoporteRoute
  VentasRoute: typeof VentasRoute
  AdminLandingRoute: typeof AdminLandingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualizar-clave': {
      id: '/actualizar-clave'
      path: '/actualizar-clave'
      fullPath: '/actualizar-clave'
      preLoaderRoute: typeof ActualizarClaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impuestos': {
      id: '/impuestos'
      path: '/impuestos'
      fullPath: '/impuestos'
      preLoaderRoute: typeof ImpuestosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitacion': {
      id: '/invitacion'
      path: '/invitacion'
      fullPath: '/invitacion'
      preLoaderRoute: typeof InvitacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-clave': {
      id: '/recuperar-clave'
      path: '/recuperar-clave'
      fullPath: '/recuperar-clave'
      preLoaderRoute: typeof RecuperarClaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soporte': {
      id: '/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof SoporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventas': {
      id: '/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof VentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/landing': {
      id: '/admin_/landing'
      path: '/admin/landing'
      fullPath: '/admin/landing'
      preLoaderRoute: typeof AdminLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clientes/': {
      id: '/admin/clientes/'
      path: '/clientes'
      fullPath: '/admin/clientes/'
      preLoaderRoute: typeof AdminClientesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes/$companyId': {
      id: '/admin/clientes/$companyId'
      path: '/clientes/$companyId'
      fullPath: '/admin/clientes/$companyId'
      preLoaderRoute: typeof AdminClientesCompanyIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ia-creditos/': {
      id: '/admin/ia-creditos/'
      path: '/ia-creditos'
      fullPath: '/admin/ia-creditos/'
      preLoaderRoute: typeof AdminIaCreditosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ia-creditos/configuracion': {
      id: '/admin/ia-creditos/configuracion'
      path: '/ia-creditos/configuracion'
      fullPath: '/admin/ia-creditos/configuracion'
      preLoaderRoute: typeof AdminIaCreditosConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ia-creditos/historial': {
      id: '/admin/ia-creditos/historial'
      path: '/ia-creditos/historial'
      fullPath: '/admin/ia-creditos/historial'
      preLoaderRoute: typeof AdminIaCreditosHistorialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/metricas/': {
      id: '/admin/metricas/'
      path: '/metricas'
      fullPath: '/admin/metricas/'
      preLoaderRoute: typeof AdminMetricasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/motor-tributario/paridad': {
      id: '/admin/motor-tributario/paridad'
      path: '/motor-tributario/paridad'
      fullPath: '/admin/motor-tributario/paridad'
      preLoaderRoute: typeof AdminMotorTributarioParidadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/motor-tributario/versiones': {
      id: '/admin/motor-tributario/versiones'
      path: '/motor-tributario/versiones'
      fullPath: '/admin/motor-tributario/versiones'
      preLoaderRoute: typeof AdminMotorTributarioVersionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planes/': {
      id: '/admin/planes/'
      path: '/planes'
      fullPath: '/admin/planes/'
      preLoaderRoute: typeof AdminPlanesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planes/$planId': {
      id: '/admin/planes/$planId'
      path: '/planes/$planId'
      fullPath: '/admin/planes/$planId'
      preLoaderRoute: typeof AdminPlanesPlanIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planes/nuevo': {
      id: '/admin/planes/nuevo'
      path: '/planes/nuevo'
      fullPath: '/admin/planes/nuevo'
      preLoaderRoute: typeof AdminPlanesNuevoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/telemetria/': {
      id: '/admin/telemetria/'
      path: '/telemetria'
      fullPath: '/admin/telemetria/'
      preLoaderRoute: typeof AdminTelemetriaIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/telemetria/api': {
      id: '/admin/telemetria/api'
      path: '/telemetria/api'
      fullPath: '/admin/telemetria/api'
      preLoaderRoute: typeof AdminTelemetriaApiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/telemetria/sii': {
      id: '/admin/telemetria/sii'
      path: '/telemetria/sii'
      fullPath: '/admin/telemetria/sii'
      preLoaderRoute: typeof AdminTelemetriaSiiRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientesCompanyIdRoute: typeof AdminClientesCompanyIdRoute
  AdminIaCreditosConfiguracionRoute: typeof AdminIaCreditosConfiguracionRoute
  AdminIaCreditosHistorialRoute: typeof AdminIaCreditosHistorialRoute
  AdminMotorTributarioParidadRoute: typeof AdminMotorTributarioParidadRoute
  AdminMotorTributarioVersionesRoute: typeof AdminMotorTributarioVersionesRoute
  AdminPlanesPlanIdRoute: typeof AdminPlanesPlanIdRoute
  AdminPlanesNuevoRoute: typeof AdminPlanesNuevoRoute
  AdminTelemetriaApiRoute: typeof AdminTelemetriaApiRoute
  AdminTelemetriaSiiRoute: typeof AdminTelemetriaSiiRoute
  AdminClientesIndexRoute: typeof AdminClientesIndexRoute
  AdminIaCreditosIndexRoute: typeof AdminIaCreditosIndexRoute
  AdminMetricasIndexRoute: typeof AdminMetricasIndexRoute
  AdminPlanesIndexRoute: typeof AdminPlanesIndexRoute
  AdminTelemetriaIndexRoute: typeof AdminTelemetriaIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminClientesCompanyIdRoute: AdminClientesCompanyIdRoute,
  AdminIaCreditosConfiguracionRoute: AdminIaCreditosConfiguracionRoute,
  AdminIaCreditosHistorialRoute: AdminIaCreditosHistorialRoute,
  AdminMotorTributarioParidadRoute: AdminMotorTributarioParidadRoute,
  AdminMotorTributarioVersionesRoute: AdminMotorTributarioVersionesRoute,
  AdminPlanesPlanIdRoute: AdminPlanesPlanIdRoute,
  AdminPlanesNuevoRoute: AdminPlanesNuevoRoute,
  AdminTelemetriaApiRoute: AdminTelemetriaApiRoute,
  AdminTelemetriaSiiRoute: AdminTelemetriaSiiRoute,
  AdminClientesIndexRoute: AdminClientesIndexRoute,
  AdminIaCreditosIndexRoute: AdminIaCreditosIndexRoute,
  AdminMetricasIndexRoute: AdminMetricasIndexRoute,
  AdminPlanesIndexRoute: AdminPlanesIndexRoute,
  AdminTelemetriaIndexRoute: AdminTelemetriaIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualizarClaveRoute: ActualizarClaveRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ComprasRoute: ComprasRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  CuentaRoute: CuentaRoute,
  DemoRoute: DemoRoute,
  DocumentosRoute: DocumentosRoute,
  ImpuestosRoute: ImpuestosRoute,
  InvitacionRoute: InvitacionRoute,
  MetasRoute: MetasRoute,
  OnboardingRoute: OnboardingRoute,
  PlanesRoute: PlanesRoute,
  RecuperarClaveRoute: RecuperarClaveRoute,
  RegistroRoute: RegistroRoute,
  SoporteRoute: SoporteRoute,
  VentasRoute: VentasRoute,
  AdminLandingRoute: AdminLandingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
